services:
  db:
    image: postgres:15
    container_name: davipay-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: davipay
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - davipay-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: davipay-backend
    environment:
      PORT: 3000
      JWT_SECRET: supersecreto
      JWT_EXPIRES_IN: 5m
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: davipay
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - davipay-network

volumes:
  postgres_data:

networks:
  davipay-network:
    driver: bridge
