name: Build Docker Artifact

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t davipay-app .

      - name: Export Docker image as tar
        run: docker save davipay-app > davipay-app.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: davipay-image
          path: davipay-app.tar
          retention-days: 1