# .github/workflows/node-cd.yml

name: Node CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: davipay_test
        options: >-
          --health-cmd="pg_isready"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: davipay_test
      NODE_ENV: test
      JWT_SECRET: supersecreto
      PORT: 3000

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t davipay-app .

      - name: Export Docker image as tar
        run: docker save davipay-app > davipay-app.tar

      - name: Load Docker image
        run: docker load < davipay-app.tar

      - name: Run container and test health
        run: |
          docker run -d --name davipay \
            --network host \
            -e DB_HOST=localhost \
            -e DB_PORT=$DB_PORT \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e DB_NAME=$DB_NAME \
            -e JWT_SECRET=$JWT_SECRET \
            -e NODE_ENV=$NODE_ENV \
            -p 3000:3000 davipay-app

          echo "Esperando container..."
          sleep 10

          curl -f http://localhost:3000/health || (docker logs davipay && exit 1)
